// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"rmmz_scenes","status":false,"description":"","parameters":{}},
{"name":"Xy_EnemyHpBar","status":true,"description":"Displays HP bars above front-facing enemies with full customization support. [by XyScripts]","parameters":{"Bar Width":"100","Bar Height":"8","Bar Y Offset":"-110","Background Color":"#000000","Fill Color":"#ff0000","Border Color":"#ffffff","Show Only When Damaged":"false","Hide On Full HP":"false","Opacity":"255","Z Index":"9"}}
];
